image:https://img.shields.io/github/license/redstarssystems/rssyslib[license,link=LICENSE]
image:https://img.shields.io/clojars/v/org.rssys.libtemplate/clj-template.svg[clojars,link=https://clojars.org/org.rssys.libtemplate/clj-template]

== Library template

:Author:            Mike Ananev
:Date:              17/04/2021
:git:               https://git-scm.com[git]
:clojure-deps-cli:  https://clojure.org/guides/getting_started[clojure deps cli]
:clj-new:           https://github.com/seancorfield/clj-new[clj-new]
:babashka:          https://github.com/babashka/babashka[babashka]
:toc:

=== Intro

This `Library template` helps you to quick start new library project using {clojure-deps-cli} and {clj-new}.

This `Library template` provides:

- project control using {babashka} tasks (v0.3.5+);
- editor configuration via `.editorconfig` file;
- configured `clj-kondo` linter;
- configured `cljstyle` formatter;
- run tests using https://github.com/lambdaisland/kaocha[kaocha].

This template will give you the following basic project workflow:
[source, bash]
----
mike@mbp02 ✗ bb tasks
build        Build deployable jar file for this project
bump         Bump version artifact in `project-version` file, level may be one of: major, minor, patch, alpha, beta, rc, release.
clean        Clean target folder
deploy       Deploy this library to Clojars
format       Format source code
install      Install deployable jar locally (requires the pom.xml file)
lint         Lint source code
outdated     Check for outdated dependencies
repl         Run Clojure repl
requirements Install project requirements
test         Run tests
----


See also:

* https://github.com/redstarssystems/rssysapp[Application template]

=== Using Library template

==== New library project

Before creating a project from this template, please install prerequisites (see below).
To create a project from this template just run:

[source, bash]
----
    clojure -X:new :template org.rssys.libtemplate :name com.example/lib01
    cd lib01
----
where `:new` is alias in `~/.clojure/deps.edn` file (see prerequisites below).

NOTE: Please, see `README.adoc` in a root folder of created project to install other tools once.


=== Install prerequisites

All these tools you need to install only once.

. Install {clojure-deps-cli} tools
.. MacOS
+
[source,bash]
----
brew install clojure/tools/clojure
----
.. Linux
+
Ensure that the following dependencies are installed in OS: `bash`, `curl`, `rlwrap`, and `Java`.
+
[source, bash]
----
curl -O https://download.clojure.org/install/linux-install-1.10.3.822.sh
chmod +x linux-install-1.10.3.822.sh
sudo ./linux-install-1.10.3.822.sh
----

. Install latest {clj-new} library to a file `~/.clojure/deps.edn`
+
[source, clojure]
----
{
 :aliases {
           :new     {:extra-deps {seancorfield/clj-new {:mvn/version "1.1.297"}}
                     :exec-fn    clj-new/create}
          }

 }
----

. Install {babashka} v0.3.5+
.. MacOS
+
[source, bash]
----
brew install borkdude/brew/babashka
----
+
.. Linux
+
[source, bash]
----
sudo bash < <(curl -s https://raw.githubusercontent.com/babashka/babashka/master/install)
----

=== License

Copyright © 2021 {Author} +
Distributed under the Eclipse Public License 2.0 or (at your option) any later version.


