== {{name}}
:git:               https://git-scm.com[git]
:clojure-deps-cli:  https://clojure.org/guides/getting_started[clojure deps cli]
:clj-new:           https://github.com/seancorfield/clj-new[clj-new]
:babashka:          https://github.com/babashka/babashka[babashka]
:toc:

Project {{name}} generated from library template https://github.com/redstarssystems/rssyslib.


=== Install project prerequisites

All these tools you need to install only once.

. Install {clojure-deps-cli} tools
.. MacOS
+
[source,bash]
----
brew install clojure/tools/clojure
----
.. Linux
+
Ensure that the following dependencies are installed in OS: `bash`, `curl`, `rlwrap`, and `Java`.
+
[source, bash]
----
curl -O https://download.clojure.org/install/linux-install-1.10.3.822.sh
chmod +x linux-install-1.10.3.822.sh
sudo ./linux-install-1.10.3.822.sh
----

. Install latest {clj-new} library to a file `~/.clojure/deps.edn`
+
[source, clojure]
----
{
 :aliases {
           :new     {:extra-deps {seancorfield/clj-new {:mvn/version "1.1.297"}}
                     :exec-fn    clj-new/create}
          }
 }
----

. Install {babashka} v0.3.5+
.. MacOS
+
[source, bash]
----
brew install borkdude/brew/babashka
----
+
.. Linux
+
[source, bash]
----
sudo bash < <(curl -s https://raw.githubusercontent.com/babashka/babashka/master/install)
----

. Run once:
+
[source,bash]
----
bb requirements
----
to install other necessary tools (MacOS only, for Linux manual instruction).

=== Project workflow

To configure project workflow scripts use `bb.edn`.

To configure project version use file `project-version`

To configure `group-id` and `artifact-id` for jar file use file `project-config`

Run `bb tasks` to show help for project workflow.

List of available tasks:
[source, bash]
----
build        Build deployable jar file for this project
bump         Bump version artifact in `project-version` file, level may be one of: major, minor, patch, alpha, beta, rc, release.
clean        Clean target folder
deploy       Deploy this library to Clojars
format       Format source code
install      Install deployable jar locally (requires the pom.xml file)
lint         Lint source code
outdated     Check for outdated dependencies
repl         Run Clojure repl
requirements Install project requirements
test         Run tests
----

=== License

Copyright © 2021 {{user}} +
Distributed under the Eclipse Public License 2.0 or (at your option) any later version.


